### ISSUE TITLE
Customize 404 and 500 error pages

### ISSUE THREAD

**Issue by climascomunicacion** [chinleung/laravel-multilingual-routes#48]
I try to customize error pages for the 404 and 500 error using Laravel 8.x , but i don't know how to handel these errors with multilingual-routes.

I have 2 baldes in /resources/views/errors/404.blade.php and /resources/views/errors/500.blade.php

I edited /app/Exceptions/Handler.php:

![Captura de pantalla 2021-03-19 a las 13 39 59](https://user-images.githubusercontent.com/79713169/111781899-aba4db00-88b8-11eb-92f0-cf291a7c91f6.png)

But when i type a no existing url (http://localhost/sdfsdfsdfsd) i keep seeing the standard error message and not my customized error page:

![Captura de pantalla 2021-03-19 a las 13 31 57](https://user-images.githubusercontent.com/79713169/111780401-a1361180-88b7-11eb-9456-23ba07377c78.png)

**Comment by chinleung** [comment]
@climascomunicacion I don't think this has anything to do with the package but I can help you debug it.

What is the error 500? You can find it in your `storage/logs`.

Also, you don't need the `if` case in your `Handler.php` since Laravel will handle it for you automatically.

https://laravel.com/docs/8.x/errors#custom-http-error-pages

**Comment by climascomunicacion** [comment]
Thanks for the replay,

debuging the error i found a bad route in one of my blades in the layout i was using to show the custom 404 error page.

I fixed that route and deleted the render function i was using in Handler.php.

Now it's working fine
